spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osikdang
    username: henry
    password: henry

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
